# This is a basic workflow to help you get started with Actions

name: Sandbox 
run-name: Sandbox pipeline - Branch `${{ github.event.client_payload.branch_ref }}` - On `${{ github.event.client_payload.time }}` - Commit `${{ github.event.client_payload.commit }}` Run by `${{ github.actor }}`
on:
    repository_dispatch:
      types: [travis_trigger]
    workflow_dispatch:
      inputs: 
        commit:
          type: string
          description: which commit to deploy
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  variables-definitions:
    # The type of runner that the job will run on
    runs-on: test
    steps:
      - name: Define variables
        id: vardef
        run: |
          printenv
          if  [[ "${{ github.event.client_payload.branch_ref }}" == "master" ]]; then
            echo "varfile=prod.tfvars" >> $GITHUB_OUTPUT
            echo "host=test" >> $GITHUB_OUTPUT
          else
            echo "varfile=sandbox.tfvars" >> $GITHUB_OUTPUT
            echo "host=test" >> $GITHUB_OUTPUT
          fi
    outputs:
      varfile: ${{ steps.vardef.outputs.varfile }}
      host: ${{ steps.vardef.outputs.host }}

  build:
    # The type of runner that the job will run on
    needs: variables-definitions
    env:
      VARFILE: ${{needs.variables-definitions.outputs.varfile}}
      HOST: ${{needs.variables-definitions.outputs.host}}
      BRANCH_REF: ${{ github.event.client_payload.branch_ref }}
    runs-on: ${{needs.variables-definitions.outputs.host}}
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
            ref: "${{ env.BRANCH_REF }}"

      - name: Run a one-line script
        env:
          BRANCH: "${{ env.BRANCH_REF }}"
        run: echo $BRANCH; tail -5 Jenkinsfile
      
      - name: test inputs
        run: |
          if  [[ "${{ inputs.commit }}" ]]; then 
            TAG="${{ inputs.commit }}"
          else
            TAG=$(git rev-parse --short HEAD)
          fi
          echo $TAG
          
      - name: Run sandbox echo
        run: |
          echo $GITHUB_CONTEXT
          echo "This is ${{ env.BRANCH_REF }}" > $VARFILE
          ls -l $VARFILE
          cat $VARFILE
          echo $HOST